version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    day: "friday"
    time: "11:00"
    open-pull-requests-limit: 10
    reviewers:
      - "h3x89"
    assignees:
      - "h3x89"
